import assert from "node:assert/strict";
import { execFile } from "node:child_process";
import { mkdir, mkdtemp, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";
import test from "node:test";
import { fileURLToPath } from "node:url";

const thisFile = fileURLToPath(import.meta.url);
const repoRoot = path.resolve(path.dirname(thisFile), "..");
const binPath = path.join(repoRoot, "bin/bandit.mjs");

test("verification-oracle-provenance validate rejects covered work without strategy or disposition", async () => {
  const repo = await createInitializedRepo();
  await writeOraclePolicy(repo);
  await writeWorkBrief(repo, "BANDIT-970", {
    title: "Covered Projection Work",
    coveredSurfaces: ["cockpit-status"],
    claims: ["current"],
    strategy: ""
  });

  const result = await runBandit(repo, [
    "verification-oracle-provenance",
    "validate",
    "BANDIT-970"
  ]);

  assert.equal(result.code, 1);
  assert.match(result.stderr, /BANDIT-970/);
  assert.match(result.stderr, /missing oracle provenance strategy or explicit disposition/);
});

test("verification-oracle-provenance validate rejects circular self-attestation for trusted claims", async () => {
  const repo = await createInitializedRepo();
  await writeOraclePolicy(repo);
  await writeWorkBrief(repo, "BANDIT-971", {
    title: "Circular Oracle Work",
    coveredSurfaces: ["session-context"],
    claims: ["trusted"],
    strategy: "independent_command_output"
  });
  await writeOracleEvidence(repo, "BANDIT-971", {
    targetSurface: "session-context",
    claim: "trusted",
    oracleType: "self_reported_or_derived",
    oracleSource: "docs/work/BANDIT-971/oracle-provenance-evidence.md",
    owner: "work_item_pm",
    independenceClass: "self_reported_or_derived",
    freshnessSource: "generated by session-context",
    command: "node ./bin/bandit.mjs session-context current --json",
    claimMapping: "session-context output is treated as its own oracle",
    sourceDriftStatus: "current"
  });

  const result = await runBandit(repo, [
    "verification-oracle-provenance",
    "validate",
    "BANDIT-971"
  ]);

  assert.equal(result.code, 1);
  assert.match(result.stderr, /circular self-attestation/);
  assert.match(result.stderr, /trusted requires independent oracle provenance/);
});

test("verification-oracle-provenance validate accepts complete independent command output evidence", async () => {
  const repo = await createInitializedRepo();
  await writeOraclePolicy(repo);
  await writeOracleTemplate(repo);
  await writeWorkBrief(repo, "BANDIT-972", {
    title: "Independent Oracle Work",
    coveredSurfaces: ["landing-verdict"],
    claims: ["safe-to-land"],
    strategy: "independent_command_output"
  });
  await writeOracleEvidence(repo, "BANDIT-972", {
    targetSurface: "landing-verdict",
    claim: "safe-to-land",
    oracleType: "independent_command_output",
    oracleSource: "node ./bin/bandit.mjs land-check BANDIT-972",
    owner: "landing_agent",
    independenceClass: "independent_command_output",
    freshnessSource: "current source head",
    command: "node ./bin/bandit.mjs land-check BANDIT-972",
    claimMapping: "land-check independently verifies landing verdict dependencies before safe-to-land",
    sourceDriftStatus: "current"
  });

  const result = await runBandit(repo, [
    "verification-oracle-provenance",
    "validate",
    "--json",
    "BANDIT-972"
  ]);

  assert.equal(result.code, 0, result.stderr);
  assert.deepEqual(JSON.parse(result.stdout), {
    status: "pass",
    policy: ".bandit/policy/verification-oracle-provenance.json",
    checked_work_items: ["BANDIT-972"],
    covered_claims: ["safe-to-land"]
  });
});

test("land-check fails closed when covered high-risk work lacks current oracle provenance evidence", async () => {
  const repo = await createInitializedRepo();
  await writeOraclePolicy(repo);
  await initGitRepo(repo);
  const sourceHead = await commitAll(repo, "Initial state");
  await writeWorkBrief(repo, "BANDIT-973", {
    title: "Landing Oracle Work",
    coveredSurfaces: ["landing-verdict"],
    claims: ["safe-to-land"],
    strategy: "independent_command_output"
  });
  await writeReviewEvidence(repo, "BANDIT-973", { sourceHead });
  await writeLandingVerdict(repo, "BANDIT-973", { sourceHead });

  const result = await runBandit(repo, ["land-check", "BANDIT-973"]);

  assert.equal(result.code, 1);
  assert.match(
    result.stderr,
    /safe-to-land requires current oracle provenance evidence for covered claim safe-to-land on landing-verdict/
  );
});

function runBandit(cwd, args) {
  return new Promise((resolve) => {
    execFile(process.execPath, [binPath, ...args], { cwd }, (error, stdout, stderr) => {
      resolve({
        code: typeof error?.code === "number" ? error.code : 0,
        stdout,
        stderr
      });
    });
  });
}

async function createInitializedRepo() {
  const repo = await mkdtemp(path.join(tmpdir(), "bandit-oracle-"));
  await runBandit(repo, ["init"]);
  await writeBasePolicies(repo);
  return repo;
}

async function writeBasePolicies(repo) {
  await writeJson(repo, ".bandit/policy/smell-triggers.json", {
    version: 1,
    smells: [
      {
        id: "BANDIT-SMELL-ADVERSARIAL-REVIEW",
        name: "Adversarial Review Required",
        category: "review_gate",
        trigger: "A PR or slice requires baseline adversarial review.",
        severity: "blocker",
        default_action: "require_qwen_review",
        escalation_target: "local-qwen-baseline",
        required_evidence: ["review-evidence.md"]
      }
    ]
  });
  await writeJson(repo, ".bandit/reviewers/local-qwen.json", {
    contract_version: 1,
    profile_id: "local-qwen-baseline",
    version: 1,
    provider: "fixture",
    provider_base_url: "http://127.0.0.1:8000/v1",
    runtime: "command",
    command: {
      executable: process.execPath,
      args: ["qwen-fixture.mjs", "{{prompt}}"]
    },
    model: "fixture-qwen",
    prompt_contract: {
      role: "read_only_adversarial_reviewer",
      required_outputs: ["verdict", "findings", "summary"]
    },
    timeout_ms: 30000,
    permissions: {
      filesystem: "read_only",
      network: "disabled",
      can_edit_files: false,
      can_request_tools: false
    },
    output_contract: {
      format: "json",
      required_fields: ["verdict", "findings", "summary"]
    },
    unavailable_runtime_behavior: "fail_closed_or_bootstrap_gap"
  });
  await writeJson(repo, ".bandit/policy/landing-agent.json", {
    version: 1,
    authority: "cli_owned_landing_agent",
    supported_actions: ["local_record"],
    cli_actions: ["local-record"],
    require_auto_land_eligible: true,
    require_clean_worktree: true,
    allowed_dirty_paths: ["docs/work/<work_item_id>/"],
    write_landing_action: true,
    allow_merge: false,
    allow_push: false,
    allow_deploy: false,
    operator_owned_boundaries: [
      "product_uat",
      "policy_change",
      "business_tradeoff",
      "cost_override",
      "risk_override"
    ]
  });
}

async function writeOraclePolicy(repo) {
  await writeJson(repo, ".bandit/policy/verification-oracle-provenance.json", {
    version: 1,
    covered_surfaces: [
      "brief",
      "review-evidence",
      "landing-verdict",
      "cockpit-status",
      "session-context",
      "trust-verify"
    ],
    covered_claims: ["pass", "safe-to-land", "trusted", "current", "ready"],
    supported_oracle_types: [
      "independent_external_artifact",
      "independent_repo_artifact",
      "independent_command_output",
      "replay_packet",
      "reviewer_finding",
      "invariant_or_property",
      "trusted_source_artifact",
      "self_reported_or_derived"
    ],
    independent_oracle_types: [
      "independent_external_artifact",
      "independent_repo_artifact",
      "independent_command_output",
      "replay_packet",
      "reviewer_finding",
      "invariant_or_property",
      "trusted_source_artifact"
    ],
    required_fields: [
      "target_surface",
      "claim",
      "oracle_type",
      "oracle_source",
      "owner_or_authority_role",
      "independence_class",
      "freshness_source",
      "claim_mapping",
      "source_drift_status"
    ],
    require_command_for_oracle_types: ["independent_command_output", "replay_packet"],
    low_risk_self_reported_claims: ["metadata-present"]
  });
}

async function writeOracleTemplate(repo) {
  await writeFileAt(
    repo,
    "docs/templates/verification-oracle-provenance.md",
    `# Verification Oracle Provenance

work_item:
target_surface:
claim:
oracle_type:
oracle_source:
owner_or_authority_role:
independence_class:
freshness_source:
command:
claim_mapping:
source_drift_status:
`
  );
}

async function writeWorkBrief(repo, id, options) {
  const coveredSurfaces = options.coveredSurfaces
    .map((surface) => `  - ${surface}`)
    .join("\n");
  const claims = options.claims.map((claim) => `  - ${claim}`).join("\n");
  await writeFileAt(
    repo,
    `docs/work/${id}/brief.md`,
    `# ${id}: ${options.title}

## Status

Ready

work_type: chore
risk_tier: high
oracle_provenance_strategy: ${options.strategy}
covered_oracle_surfaces:
${coveredSurfaces}
covered_oracle_claims:
${claims}
`
  );
}

async function writeOracleEvidence(repo, id, evidence) {
  await writeFileAt(
    repo,
    `docs/work/${id}/oracle-provenance-evidence.md`,
    `# Oracle Provenance Evidence: ${id}

contract_version: 1
work_item: ${id}
target_surface: ${evidence.targetSurface}
claim: ${evidence.claim}
oracle_type: ${evidence.oracleType}
oracle_source: ${evidence.oracleSource}
owner_or_authority_role: ${evidence.owner}
independence_class: ${evidence.independenceClass}
freshness_source: ${evidence.freshnessSource}
command: ${evidence.command}
claim_mapping: ${evidence.claimMapping}
source_drift_status: ${evidence.sourceDriftStatus}
`
  );
}

async function writeReviewEvidence(repo, id, options = {}) {
  await writeFileAt(
    repo,
    `docs/work/${id}/review-evidence.md`,
    `# Review Evidence: ${id}

contract_version: 1
work_item: ${id}
source_head: ${options.sourceHead ?? "unknown"}
verification_state: pass
verification_evidence:
  - node --test test/verification-oracle-provenance.test.mjs
coderabbit_state: bootstrap_gap
coderabbit_replacement_evidence:
  - Manual PM review replaces unavailable final gates during bootstrap.
local_qwen_state: bootstrap_gap
local_qwen_replacement_evidence:
  - Local Qwen runtime is unavailable during bootstrap.
escalated_review_required: false
escalated_review_state: not_applicable
escalated_review_rationale: No smell trigger requires escalation beyond baseline.
pm_disposition: pass
pm_disposition_rationale: No unresolved reviewer findings.
non_blocking_findings_routing:
  - none
operator_input_status: none_required
uat_status: not_applicable
clean_code_status: pass
source_drift_status: current
bootstrap_gaps:
  - Manual PM review replaces unavailable final gates during bootstrap.
`
  );
}

async function writeLandingVerdict(repo, id, options = {}) {
  await writeFileAt(
    repo,
    `docs/work/${id}/landing-verdict.md`,
    `# Landing Verdict: ${id}

contract_version: 1
work_item: ${id}
source_head: ${options.sourceHead ?? "unknown"}
review_evidence: docs/work/${id}/review-evidence.md
tests_status: pass
clean_code_status: pass
coderabbit_state: bootstrap_gap
local_qwen_state: bootstrap_gap
escalated_review_state: not_applicable
uat_status: not_applicable
source_drift_status: current
operator_input_status: none_required
landing_agent_state: bootstrap_gap
landing_agent_replacement_evidence:
  - Manual PM review replaces unavailable final gates during bootstrap.
final_verdict: safe-to-land
rationale: Evidence is explicit and unavailable final gates are recorded as bootstrap gaps.
`
  );
}

async function initGitRepo(repo) {
  await execGit(repo, ["init"]);
  await execGit(repo, ["config", "user.email", "bandit@example.test"]);
  await execGit(repo, ["config", "user.name", "Bandit Test"]);
}

async function commitAll(repo, message) {
  await execGit(repo, ["add", "."]);
  await execGit(repo, ["commit", "-m", message]);
  const result = await execGit(repo, ["rev-parse", "HEAD"]);
  return result.stdout.trim();
}

function execGit(repo, args) {
  return new Promise((resolve, reject) => {
    execFile("git", args, { cwd: repo }, (error, stdout, stderr) => {
      if (error) {
        reject(new Error(stderr || error.message));
        return;
      }
      resolve({ stdout, stderr });
    });
  });
}

async function writeJson(repo, displayPath, value) {
  await writeFileAt(repo, displayPath, `${JSON.stringify(value, null, 2)}\n`);
}

async function writeFileAt(repo, displayPath, content) {
  const destination = path.join(repo, displayPath);
  await mkdir(path.dirname(destination), { recursive: true });
  await writeFile(destination, content, "utf8");
}
